version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: pmsystem-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - pmsystem-network
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    container_name: pmsystem-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - pmsystem-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pmsystem-app
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - pmsystem-network
    volumes:
      - app_data:/app/data
      - ./:/app
      - /app/node_modules

networks:
  pmsystem-network:
    driver: bridge

volumes:
  postgres_data:
    name: pmsystem-postgres-data
  app_data:
    name: pmsystem-app-data

